/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#795a1b",
          50: "#fef9ee",
          100: "#fcd186",
          200: "#edc37a",
          300: "#d4a84e",
          400: "#b8882e",
          500: "#795a1b",
          600: "#6d4f10",
          700: "#5c4310",
          800: "#4b3400",
          900: "#3a2800",
          container: "#fcd186",
          dim: "#6c4e0f",
        },
        surface: {
          DEFAULT: "#faf9f7",
          dim: "#d9dad8",
          bright: "#faf9f7",
          "container-lowest": "#ffffff",
          "container-low": "#f4f4f1",
          container: "#edeeec",
          "container-high": "#e7e8e6",
          "container-highest": "#e1e3e0",
        },
        "on-surface": "#303331",
        "on-surface-variant": "#5d605e",
        "on-primary": "#fff8f1",
        outline: "#797b79",
        "outline-variant": "#b0b2b0",
        secondary: "#6e5d40",
        "secondary-container": "#f7dfbb",
        tertiary: "#845335",
        "tertiary-container": "#fcbb95",
        error: {
          DEFAULT: "#a73b21",
          container: "#fd795a",
        },
      },
      fontFamily: {
        headline: [
          "Plus Jakarta Sans",
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "PingFang SC",
          "Hiragino Sans GB",
          "Microsoft YaHei",
          "sans-serif",
        ],
        body: [
          "Manrope",
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "PingFang SC",
          "Hiragino Sans GB",
          "Microsoft YaHei",
          "sans-serif",
        ],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
      },
      boxShadow: {
        soft: "0 4px 20px rgba(0, 0, 0, 0.03)",
        card: "0 2px 8px rgba(0, 0, 0, 0.04)",
        float: "0 8px 32px rgba(121, 90, 27, 0.08)",
        glass: "0 8px 32px rgba(0, 0, 0, 0.06)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
