/**
 * Convert draw.io XML into an editable PPTX with individual shapes,
 * images, text boxes and orthogonal arrows as separate PowerPoint objects.
 *
 * Handles the component categories generated by FullGenOrchestrator:
 * STAGE_BOX, ILLUSTRATION (base64 images), TEXT, ARROW (flexArrow),
 * and connection edges with orthogonal routing.
 */
import PptxGenJS from "pptxgenjs";

// ---------------------------------------------------------------------------
// Style parsing
// ---------------------------------------------------------------------------

export function parseStyleStr(raw: string): Record<string, string> {
  const result: Record<string, string> = {};
  if (!raw) return result;

  let i = 0;
  while (i < raw.length) {
    while (i < raw.length && raw[i] === ";") i++;
    if (i >= raw.length) break;

    const eqIdx = raw.indexOf("=", i);
    const semiIdx = raw.indexOf(";", i);

    if (eqIdx < 0 || (semiIdx >= 0 && semiIdx < eqIdx)) {
      const flag = raw.substring(i, semiIdx >= 0 ? semiIdx : raw.length).trim();
      if (flag) result[flag] = "1";
      i = semiIdx >= 0 ? semiIdx + 1 : raw.length;
      continue;
    }

    const key = raw.substring(i, eqIdx).trim();
    i = eqIdx + 1;

    if (key === "image" && raw.substring(i, i + 5) === "data:") {
      let end = i;
      while (end < raw.length) {
        const ns = raw.indexOf(";", end);
        if (ns < 0) {
          end = raw.length;
          break;
        }
        if (/^[a-zA-Z][\w]*=/.test(raw.substring(ns + 1))) {
          end = ns;
          break;
        }
        end = ns + 1;
      }
      result[key] = raw.substring(i, end);
      i = end;
    } else {
      const valEnd = raw.indexOf(";", i);
      result[key] = raw.substring(i, valEnd >= 0 ? valEnd : raw.length).trim();
      i = valEnd >= 0 ? valEnd + 1 : raw.length;
    }
  }
  return result;
}

export function stripHtml(html: string): string {
  if (!html) return "";
  const tmp = document.createElement("div");
  tmp.innerHTML = html;
  return tmp.textContent || tmp.innerText || "";
}

export function toHex6(color: string): string {
  if (!color || color === "none" || color === "default") return "";
  const c = color.startsWith("#") ? color.slice(1) : color;
  if (c.length === 3) return c[0] + c[0] + c[1] + c[1] + c[2] + c[2];
  return c.toUpperCase();
}

/**
 * Extract embedded image data URL from either the style `image=` property
 * or an HTML `<img src="data:...">` tag in the cell value.
 * Uses DOM parsing instead of regex for robustness with large base64 payloads.
 */
export function extractImageUrl(
  style: Record<string, string>,
  rawValue: string,
): string | undefined {
  // 1) style.image = data:image/...
  if (style.image) {
    let url = style.image;

    // SVG wrapper around a PNG (generated by xml_assembler) — extract
    // the inner PNG directly because browser Image sandbox blocks
    // data: URIs inside SVG <image> elements.
    if (url.startsWith("data:image/svg+xml,") && url.includes("%")) {
      let decoded: string;
      try {
        decoded = decodeURIComponent(url.substring("data:image/svg+xml,".length));
      } catch {
        decoded = "";
      }
      const pngMatch = decoded.match(/xlink:href="(data:image\/png;base64,[^"]+)"/);
      if (pngMatch) return pngMatch[1];
      // No inner PNG — keep as SVG for rasterization (e.g. bioicons)
      return url;
    }

    if (url.includes("%3B") || url.includes("%2C")) {
      try {
        url = decodeURIComponent(url);
      } catch {
        /* keep as-is */
      }
    }
    if (url.startsWith("data:image/")) return url;
  }

  // 2) HTML <img src="data:..."> embedded in the cell value
  if (rawValue.includes("<img")) {
    const tmp = document.createElement("div");
    tmp.innerHTML = rawValue;
    const img = tmp.querySelector("img");
    if (img?.src?.startsWith("data:image/")) return img.src;
  }

  return undefined;
}

// ---------------------------------------------------------------------------
// SVG → PNG conversion (pptxgenjs only supports raster images)
// ---------------------------------------------------------------------------

function svgDataUrlToPng(
  svgDataUrl: string,
  w: number,
  h: number,
): Promise<string> {
  const RENDER_W = Math.max(w, 200);
  const RENDER_H = Math.max(h, 200);

  // Normalise to base64-encoded data URL so '#' in SVG content
  // is not misinterpreted as a URL fragment by the browser.
  let safeSrc = svgDataUrl;
  const commaIdx = svgDataUrl.indexOf(",");
  if (commaIdx > 0 && !svgDataUrl.includes(";base64,")) {
    let svgBody = svgDataUrl.substring(commaIdx + 1);
    if (svgBody.includes("%")) {
      try { svgBody = decodeURIComponent(svgBody); } catch { /* keep */ }
    }
    safeSrc = "data:image/svg+xml;base64," + btoa(unescape(encodeURIComponent(svgBody)));
  }

  return new Promise((resolve, reject) => {
    const img = new window.Image();
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = RENDER_W;
      canvas.height = RENDER_H;
      const ctx = canvas.getContext("2d");
      if (!ctx) {
        reject(new Error("canvas 2d context unavailable"));
        return;
      }
      ctx.drawImage(img, 0, 0, RENDER_W, RENDER_H);
      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = () => reject(new Error("SVG rasterization failed"));
    img.src = safeSrc;
  });
}

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

interface Vertex {
  id: string;
  parentId: string;
  x: number;
  y: number;
  w: number;
  h: number;
  absX: number;
  absY: number;
  label: string;
  rawValue: string;
  style: Record<string, string>;
  imageUrl?: string;
  isGroup: boolean;
  isFlexArrow: boolean;
}

interface Edge {
  id: string;
  sourceId?: string;
  targetId?: string;
  label: string;
  style: Record<string, string>;
  srcPt?: { x: number; y: number };
  tgtPt?: { x: number; y: number };
  waypoints: Pt[];
}

// Slide box in inches
interface Box {
  x: number;
  y: number;
  w: number;
  h: number;
}

// ---------------------------------------------------------------------------
// Orthogonal edge routing
// ---------------------------------------------------------------------------

interface Pt {
  x: number;
  y: number;
}

/**
 * Find the point on a box's border closest to the direction of `target`.
 * Returns the midpoint of the nearest face (left/right/top/bottom).
 */
function snapToBorder(box: Box, target: Pt): Pt {
  const cx = box.x + box.w / 2;
  const cy = box.y + box.h / 2;
  const dx = target.x - cx;
  const dy = target.y - cy;

  if (box.w === 0 && box.h === 0) return { x: cx, y: cy };

  const scaleX = box.w > 0 ? Math.abs(dx) / (box.w / 2) : 0;
  const scaleY = box.h > 0 ? Math.abs(dy) / (box.h / 2) : 0;

  if (scaleX > scaleY) {
    return { x: dx > 0 ? box.x + box.w : box.x, y: cy };
  }
  return { x: cx, y: dy > 0 ? box.y + box.h : box.y };
}

/**
 * Compute an orthogonal (right-angle) route between the borders of two boxes,
 * similar to draw.io's orthogonalEdgeStyle.
 */
function orthogonalRoute(src: Box, tgt: Box): Pt[] {
  const srcCx = src.x + src.w / 2;
  const srcCy = src.y + src.h / 2;
  const tgtCx = tgt.x + tgt.w / 2;
  const tgtCy = tgt.y + tgt.h / 2;

  const dx = tgtCx - srcCx;
  const dy = tgtCy - srcCy;
  const GAP = 0;

  if (Math.abs(dx) >= Math.abs(dy)) {
    // Primarily horizontal connection
    const exitX = dx > 0 ? src.x + src.w + GAP : src.x - GAP;
    const entryX = dx > 0 ? tgt.x - GAP : tgt.x + tgt.w + GAP;
    const exitY = srcCy;
    const entryY = tgtCy;

    if (Math.abs(exitY - entryY) < 0.03) {
      return [
        { x: exitX, y: exitY },
        { x: entryX, y: entryY },
      ];
    }
    const midX = (exitX + entryX) / 2;
    return [
      { x: exitX, y: exitY },
      { x: midX, y: exitY },
      { x: midX, y: entryY },
      { x: entryX, y: entryY },
    ];
  } else {
    // Primarily vertical connection
    const exitY = dy > 0 ? src.y + src.h + GAP : src.y - GAP;
    const entryY = dy > 0 ? tgt.y - GAP : tgt.y + tgt.h + GAP;
    const exitX = srcCx;
    const entryX = tgtCx;

    if (Math.abs(exitX - entryX) < 0.03) {
      return [
        { x: exitX, y: exitY },
        { x: entryX, y: entryY },
      ];
    }
    const midY = (exitY + entryY) / 2;
    return [
      { x: exitX, y: exitY },
      { x: exitX, y: midY },
      { x: entryX, y: midY },
      { x: entryX, y: entryY },
    ];
  }
}

/**
 * Render a polyline as multiple pptxgenjs line segments.
 * Only the last segment gets the arrowhead.
 */
function addPolyline(
  slide: PptxGenJS.Slide,
  points: Pt[],
  color: string,
  width: number,
  dashed: boolean,
  arrowEnd: boolean,
) {
  // Extend each segment slightly at corners to eliminate visual gaps
  const EXT = 0.01; // inches of overlap at joints

  for (let i = 0; i < points.length - 1; i++) {
    const p1 = { ...points[i] };
    const p2 = { ...points[i + 1] };
    const isFirst = i === 0;
    const isLast = i === points.length - 2;

    // Extend intermediate joints to overlap with neighboring segments
    if (!isFirst) {
      if (Math.abs(p2.x - p1.x) > Math.abs(p2.y - p1.y)) {
        p1.x += p2.x > p1.x ? -EXT : EXT;
      } else {
        p1.y += p2.y > p1.y ? -EXT : EXT;
      }
    }
    if (!isLast) {
      if (Math.abs(p2.x - p1.x) > Math.abs(p2.y - p1.y)) {
        p2.x += p2.x > p1.x ? EXT : -EXT;
      } else {
        p2.y += p2.y > p1.y ? EXT : -EXT;
      }
    }

    const segW = Math.abs(p2.x - p1.x);
    const segH = Math.abs(p2.y - p1.y);
    if (segW < 0.003 && segH < 0.003) continue;

    slide.addShape("line" as never, {
      x: Math.min(p1.x, p2.x),
      y: Math.min(p1.y, p2.y),
      w: segW || 0.005,
      h: segH || 0.005,
      line: {
        color: color || "666666",
        width,
        dashType: dashed ? "lgDash" : undefined,
        endArrowType: isLast && arrowEnd ? "triangle" : undefined,
      },
      flipH: p2.x < p1.x,
      flipV: p2.y < p1.y,
    } as never);
  }
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export async function exportDrawioToPptx(xml: string): Promise<void> {
  const doc = new DOMParser().parseFromString(xml, "text/xml");
  const cells = Array.from(doc.querySelectorAll("mxCell"));

  const vertices: Vertex[] = [];
  const edges: Edge[] = [];
  const idMap = new Map<string, Vertex>();

  // Detect groups (cells that are parents of other vertex cells)
  const vertexIds = new Set(
    cells
      .filter((c) => c.getAttribute("vertex") === "1")
      .map((c) => c.getAttribute("id") || ""),
  );
  const parentUsage = new Map<string, number>();
  for (const c of cells) {
    const pid = c.getAttribute("parent") || "";
    if (vertexIds.has(pid)) {
      parentUsage.set(pid, (parentUsage.get(pid) || 0) + 1);
    }
  }

  for (const cell of cells) {
    const parent = cell.parentElement;
    const isWrapped = parent?.tagName === "UserObject" || parent?.tagName === "object";
    const id = (isWrapped ? parent!.getAttribute("id") : cell.getAttribute("id")) || "";
    const rawStyle = cell.getAttribute("style") || "";
    const style = parseStyleStr(rawStyle);
    const rawValue = (isWrapped ? parent!.getAttribute("label") : cell.getAttribute("value")) || "";
    const label = stripHtml(rawValue);

    if (cell.getAttribute("vertex") === "1") {
      const geo = cell.querySelector("mxGeometry");
      if (!geo) continue;
      const x = parseFloat(geo.getAttribute("x") || "0");
      const y = parseFloat(geo.getAttribute("y") || "0");
      const w = parseFloat(geo.getAttribute("width") || "0");
      const h = parseFloat(geo.getAttribute("height") || "0");
      if (w === 0 && h === 0) continue;

      const imageUrl = extractImageUrl(style, rawValue);
      const isFlexArrow =
        style.shape === "flexArrow" || style.shape === "mxgraph.arrows2.arrow";

      const v: Vertex = {
        id,
        parentId: cell.getAttribute("parent") || "1",
        x,
        y,
        w,
        h,
        absX: x,
        absY: y,
        label,
        rawValue,
        style,
        imageUrl,
        isGroup: (parentUsage.get(id) || 0) > 0,
        isFlexArrow,
      };
      vertices.push(v);
      idMap.set(id, v);
    }

    if (cell.getAttribute("edge") === "1") {
      const geo = cell.querySelector("mxGeometry");
      const srcEl = geo?.querySelector('mxPoint[as="sourcePoint"]');
      const tgtEl = geo?.querySelector('mxPoint[as="targetPoint"]');

      const waypoints: Pt[] = [];
      const pointsArray = geo?.querySelector('Array[as="points"]');
      if (pointsArray) {
        for (const pt of Array.from(pointsArray.querySelectorAll("mxPoint"))) {
          waypoints.push({
            x: parseFloat(pt.getAttribute("x") || "0"),
            y: parseFloat(pt.getAttribute("y") || "0"),
          });
        }
      }

      edges.push({
        id,
        sourceId: cell.getAttribute("source") || undefined,
        targetId: cell.getAttribute("target") || undefined,
        label,
        style,
        srcPt: srcEl
          ? {
              x: parseFloat(srcEl.getAttribute("x") || "0"),
              y: parseFloat(srcEl.getAttribute("y") || "0"),
            }
          : undefined,
        tgtPt: tgtEl
          ? {
              x: parseFloat(tgtEl.getAttribute("x") || "0"),
              y: parseFloat(tgtEl.getAttribute("y") || "0"),
            }
          : undefined,
        waypoints,
      });
    }
  }

  // Resolve absolute positions (child coords are relative to parent)
  for (const v of vertices) {
    let ax = v.x,
      ay = v.y,
      pid = v.parentId;
    while (pid && pid !== "0" && pid !== "1") {
      const p = idMap.get(pid);
      if (!p) break;
      ax += p.x;
      ay += p.y;
      pid = p.parentId;
    }
    v.absX = ax;
    v.absY = ay;
  }

  if (vertices.length === 0) return;

  // Bounding box
  let minX = Infinity,
    minY = Infinity,
    maxX = -Infinity,
    maxY = -Infinity;
  for (const v of vertices) {
    minX = Math.min(minX, v.absX);
    minY = Math.min(minY, v.absY);
    maxX = Math.max(maxX, v.absX + v.w);
    maxY = Math.max(maxY, v.absY + v.h);
  }

  const dw = maxX - minX || 1;
  const dh = maxY - minY || 1;

  // Scale to LAYOUT_WIDE slide (13.33 x 7.5 inches)
  const SLIDE_W = 13.33;
  const SLIDE_H = 7.5;
  const MARGIN = 0.35;
  const uW = SLIDE_W - 2 * MARGIN;
  const uH = SLIDE_H - 2 * MARGIN;
  const scale = Math.min(uW / dw, uH / dh);
  const ox = MARGIN + (uW - dw * scale) / 2;
  const oy = MARGIN + (uH - dh * scale) / 2;

  const sx = (px: number) => ox + (px - minX) * scale;
  const sy = (py: number) => oy + (py - minY) * scale;
  const sw = (px: number) => px * scale;

  // draw.io: 1 unit = 1px ≈ 1/96 inch; fontSize is in CSS pt (1pt = 1/72 inch).
  // To keep text proportional to shapes after scaling:
  //   pptxFontSize = drawioFontSize × 96 × scale
  const fontScale = 96 * scale;

  /** Scale a draw.io fontSize (pt) to PPT fontSize (pt), clamped to readable range. */
  const fs = (drawioSize: number) =>
    Math.round(Math.max(4, Math.min(drawioSize * fontScale, 48)) * 10) / 10;

  /** Get the slide-space bounding box for a vertex */
  function slideBox(v: Vertex): Box {
    return { x: sx(v.absX), y: sy(v.absY), w: sw(v.w), h: sw(v.h) };
  }

  // Create PPTX
  const pres = new PptxGenJS();
  pres.layout = "LAYOUT_WIDE";
  const slide = pres.addSlide();
  slide.background = { color: "FFFFFF" };

  const groups = vertices.filter((v) => v.isGroup);
  const nonGroups = vertices.filter((v) => !v.isGroup);

  // ── 1) Groups (background containers) ──
  for (const v of groups) {
    const b = slideBox(v);
    const fill = v.style.fillColor;
    const stroke = v.style.strokeColor;
    const isRounded = v.style.rounded === "1";

    const opts: Record<string, unknown> = { x: b.x, y: b.y, w: b.w, h: b.h };
    if (fill && fill !== "none") opts.fill = { color: toHex6(fill) };
    if (stroke && stroke !== "none")
      opts.line = { color: toHex6(stroke), width: 0.5 };
    if (isRounded) opts.rectRadius = 0.08;

    slide.addShape(
      (isRounded ? "roundRect" : "rect") as never,
      opts as never,
    );

    if (v.label) {
      const fontSize = fs(parseFloat(v.style.fontSize || "13"));
      slide.addText(v.label, {
        x: b.x + 0.05,
        y: b.y + 0.02,
        w: b.w - 0.1,
        h: Math.max(0.2, fontSize / 72 * 2.5),
        fontSize,
        color: toHex6(v.style.fontColor || "#333333"),
        bold: (parseInt(v.style.fontStyle || "0") & 1) !== 0,
        align: "left",
        valign: "top",
      });
    }
  }

  // ── 2) Non-group vertices ──
  for (const v of nonGroups) {
    const b = slideBox(v);

    // 2a) flexArrow shapes → PPT arrow shapes
    if (v.isFlexArrow) {
      const dir = v.style.direction || "east";
      const arrowMap: Record<string, string> = {
        south: "downArrow",
        north: "upArrow",
        west: "leftArrow",
        east: "rightArrow",
      };
      const shapeName = arrowMap[dir] || "rightArrow";
      const fill = v.style.fillColor || "#616161";
      const stroke = v.style.strokeColor || fill;

      slide.addShape(shapeName as never, {
        x: b.x,
        y: b.y,
        w: b.w,
        h: b.h,
        fill: { color: toHex6(fill) },
        line: { color: toHex6(stroke), width: 0.5 },
      } as never);

      if (v.label) {
        slide.addText(v.label, {
          x: b.x,
          y: b.y,
          w: b.w,
          h: b.h,
          fontSize: fs(parseFloat(v.style.fontSize || "10")),
          color: "FFFFFF",
          align: "center",
          valign: "middle",
          bold: true,
        });
      }
      continue;
    }

    // 2b) Image cells (base64 PNG/SVG embedded in value HTML)
    if (v.imageUrl) {
      try {
        let imgData = v.imageUrl;
        if (imgData.startsWith("data:image/svg")) {
          imgData = await svgDataUrlToPng(imgData, v.w, v.h);
        }
        slide.addImage({ data: imgData, x: b.x, y: b.y, w: b.w, h: b.h });
      } catch {
        /* skip broken images */
      }
      if (v.label) {
        const labelFs = fs(parseFloat(v.style.fontSize || "10"));
        slide.addText(v.label, {
          x: b.x - 0.15,
          y: b.y + b.h + 0.02,
          w: b.w + 0.3,
          h: Math.max(0.18, labelFs / 72 * 2),
          fontSize: labelFs,
          color: toHex6(v.style.fontColor || "#555555"),
          align: "center",
          valign: "top",
        });
      }
      continue;
    }

    // 2c) Shape / text cells
    const fill = v.style.fillColor;
    const stroke = v.style.strokeColor;
    const isRounded = v.style.rounded === "1";
    const isEllipse =
      v.style.ellipse === "1" || v.style.shape === "ellipse";

    if (v.label) {
      const fontSize = fs(parseFloat(v.style.fontSize || "14"));
      const textOpts: Record<string, unknown> = {
        x: b.x,
        y: b.y,
        w: b.w,
        h: b.h,
        fontSize,
        color: toHex6(v.style.fontColor || "#333333"),
        align: v.style.align || "center",
        valign: v.style.verticalAlign || "middle",
        fontFace: v.style.fontFamily || "Arial",
        bold: (parseInt(v.style.fontStyle || "0") & 1) !== 0,
        italic: (parseInt(v.style.fontStyle || "0") & 2) !== 0,
        wrap: true,
        margin: [2, 4, 2, 4],
      };
      if (fill && fill !== "none") textOpts.fill = { color: toHex6(fill) };
      if (stroke && stroke !== "none")
        textOpts.line = { color: toHex6(stroke), width: 0.5 };
      if (isRounded) {
        textOpts.rectRadius = 0.08;
        textOpts.shape = "roundRect";
      }
      if (isEllipse) textOpts.shape = "ellipse";

      slide.addText(v.label, textOpts as never);
    } else if ((fill && fill !== "none") || (stroke && stroke !== "none")) {
      const shapeName = isEllipse
        ? "ellipse"
        : isRounded
          ? "roundRect"
          : "rect";
      const opts: Record<string, unknown> = {
        x: b.x,
        y: b.y,
        w: b.w,
        h: b.h,
      };
      if (fill && fill !== "none") opts.fill = { color: toHex6(fill) };
      if (stroke && stroke !== "none")
        opts.line = { color: toHex6(stroke), width: 0.5 };
      if (isRounded) opts.rectRadius = 0.08;

      slide.addShape(shapeName as never, opts as never);
    }
  }

  // ── 3) Edges with orthogonal routing ──
  for (const e of edges) {
    const src = e.sourceId ? idMap.get(e.sourceId) : null;
    const tgt = e.targetId ? idMap.get(e.targetId) : null;

    const lineColor = toHex6(e.style.strokeColor || "#666666") || "666666";
    const lineWidth = Math.max(
      0.5,
      parseFloat(e.style.strokeWidth || "2") * 0.5,
    );
    const dashed = e.style.dashed === "1";
    const hasArrow =
      e.style.endArrow !== "none" && e.style.endArrow !== "0";

    const slidePts: Pt[] = [];

    if (src && tgt) {
      const srcBox = slideBox(src);
      const tgtBox = slideBox(tgt);

      if (e.waypoints.length > 0) {
        const wps = e.waypoints.map((p) => ({ x: sx(p.x), y: sy(p.y) }));
        slidePts.push(snapToBorder(srcBox, wps[0]));
        slidePts.push(...wps);
        slidePts.push(snapToBorder(tgtBox, wps[wps.length - 1]));
      } else {
        slidePts.push(...orthogonalRoute(srcBox, tgtBox));
      }
    } else {
      // Build start point
      if (src) {
        const srcBox = slideBox(src);
        const firstWp = e.waypoints.length > 0
          ? { x: sx(e.waypoints[0].x), y: sy(e.waypoints[0].y) }
          : null;
        if (firstWp) {
          slidePts.push(snapToBorder(srcBox, firstWp));
        } else {
          slidePts.push({ x: srcBox.x + srcBox.w / 2, y: srcBox.y + srcBox.h / 2 });
        }
      } else if (e.srcPt) {
        slidePts.push({ x: sx(e.srcPt.x), y: sy(e.srcPt.y) });
      } else {
        continue;
      }

      // Add intermediate waypoints
      for (const wp of e.waypoints) {
        slidePts.push({ x: sx(wp.x), y: sy(wp.y) });
      }

      // Build end point
      if (tgt) {
        const tgtBox = slideBox(tgt);
        const lastPt = slidePts[slidePts.length - 1];
        slidePts.push(snapToBorder(tgtBox, lastPt));
      } else if (e.tgtPt) {
        slidePts.push({ x: sx(e.tgtPt.x), y: sy(e.tgtPt.y) });
      } else {
        continue;
      }
    }

    if (slidePts.length >= 2) {
      addPolyline(slide, slidePts, lineColor, lineWidth, dashed, hasArrow !== false);
    }

    // Edge label — position at midpoint of the route
    if (e.label && slidePts.length >= 2) {
      const midIdx = Math.floor(slidePts.length / 2);
      const mp1 = slidePts[midIdx - 1];
      const mp2 = slidePts[midIdx];
      const mx = (mp1.x + mp2.x) / 2;
      const my = (mp1.y + mp2.y) / 2;
      const edgeFs = fs(parseFloat(e.style.fontSize || "10"));
      const labelW = Math.max(0.6, edgeFs / 72 * e.label.length * 0.8);
      slide.addText(e.label, {
        x: mx - labelW / 2,
        y: my - edgeFs / 72,
        w: labelW,
        h: edgeFs / 72 * 2,
        fontSize: edgeFs,
        color: toHex6(e.style.fontColor || "#666666"),
        align: "center",
        valign: "middle",
      });
    }
  }

  await pres.writeFile({ fileName: "diagram.pptx" });
}
